### ISSUE TITLE
FSCKFIX not being set correctly

### ISSUE THREAD

**Issue by mattbostock** [alphagov/puppet-rcs#18]
puppet-rcs [forces all options to upper case](https://github.com/alphagov/puppet-rcs/blob/69e598b01519861d982a7315a5715cf541426c3c/templates/etc/default/rcS.erb#L20) and uses upper case for its [defaults](https://github.com/alphagov/puppet-rcs/blob/69e598b01519861d982a7315a5715cf541426c3c/manifests/init.pp#L65).

The Upstart service that makes use of the 'FSCKFIX' option is 'mountall', however mountall expects FSCKFIX to use lowercase "yes":

```
mattbostock@preview-jumpbox-1:~$ grep FSCKFIX /etc/init/mountall.conf
    [ "$FSCKFIX" = "yes" ] && fsck_fix="--fsck-fix"
```

This means that the FSCKFIX option is not being enabled:

```
mattbostock@preview-jumpbox-1:~$ . /etc/default/rcS
mattbostock@preview-jumpbox-1:~$ echo $FSCKFIX
YES
mattbostock@preview-jumpbox-1:~$ [ "$FSCKFIX" = "yes" ]; echo $?
1
```

**Comment by ajlanghorn** [comment]
This is odd, since the default in /etc/default/rcS on a stock Precise or Trusty installation is to use capital letters from memory. Assuming that's the case, how did mountall ever work with this?

The quick fix would be to remove the upcase method from the ERB template, but I think it would be interesting to see why mountall fails with upcased values.

**Comment by mattbostock** [comment]
@ajlanghorn: Please go back to your holiday.

**Comment by ajlanghorn** [comment]
GitHub should stop emailing me when you raise an issue then :)

**Comment by rjw1** [comment]
this suggests that you have work repos talking to your personal email account. you should stop that :)

**Comment by ajlanghorn** [comment]
I think it's a throwback from when this was transferred from ajlanghorn to alphagov. Who knows?!

**Comment by ajlanghorn** [comment]
Okay, I was wrong. I spun up a VM in Vagrant from the ubuntu/trusty64 Atlas box, and the default /etc/default/rcS uses lowercase values. PR coming up. Thanks for flagging this, @mattbostock.
